---
- name: add the ldiff
  template:
    src: orgRole.ldif.j2
    dest: /tmp/1.ldif

- name: Add an Organizational role to your ldap
  shell: "ldapadd -a -x -D 'cn=admin,{{ldap_root_dn_suffix}}' -w {{ldap_server_rootpw}} -f /tmp/1.ldif"
  ignore_errors: yes

- name: add the admin ldiff
  template:
    src: admin.ldif.j2
    dest: /tmp/2.ldif

- name: Add the admin user
  shell: "ldapadd -a -x -D 'cn=admin,{{ldap_root_dn_suffix}}' -w {{ldap_server_rootpw}} -f /tmp/2.ldif"
  ignore_errors: yes

- name: add some OUs to your ldap
  template:
    src: ous.ldif.j2
    dest: /tmp/3.ldif

- name: add some OUs to your ldap
  shell: "ldapadd -a -x -D 'cn=admin,{{ldap_root_dn_suffix}}' -w {{ldap_server_rootpw}} -f /tmp/3.ldif"
  ignore_errors: yes

- name: add another user ldiff
  template:
    src: user.ldif.j2
    dest: /tmp/4.ldif

- name: add another user
  shell: "ldapadd -a -x -D 'cn=admin,{{ldap_root_dn_suffix}}' -w {{ldap_server_rootpw}} -f /tmp/4.ldif"
  ignore_errors: yes

- name: add a group ldiff
  template:
    src: group.hadoop.ldif.j2
    dest: /tmp/5.ldif

- name: add a group to your ldap
  shell: "ldapadd -a -x -D 'cn=admin,{{ldap_root_dn_suffix}}' -w {{ldap_server_rootpw}} -f /tmp/5.ldif"
  ignore_errors: yes

- name: add a user to group ldiff
  template:
    src: user_to_group.ldif.j2
    dest: /tmp/6.ldif

- name: add a user to group
  shell: "ldapadd -a -x -D 'cn=admin,{{ldap_root_dn_suffix}}' -w {{ldap_server_rootpw}} -f /tmp/6.ldif"
  ignore_errors: yes