---
# tasks file for common

- name: enable epel-release repo (or need to pull python-pip to local repo)
  yum:
    name: epel-release
    state: present

- name: ensure core packages are installed
  yum:
    name: "{{common_yum_packages}}"
    state: present

- name: copy java.sh
  template:
    src: 'java.sh.j2'
    dest: '/etc/profile.d/java.sh'
    mode: '644'

- name: disable selinux
  shell: sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/selinux/config

- name: disable selinux
  shell: sed -i 's/SELINUX=enforcing/SELINUX=disabled/' /etc/sysconfig/selinux

- name: Check if Iptables Service Exists
  stat: path=/usr/lib/systemd/system/iptables.service
  register: iptables_status

- name: disabe iptables
  service: name=iptables state=stopped
  when: iptables_status.stat.exists

- name: disbale  iptables on boot
  service: name=iptables enabled=no
  when: iptables_status.stat.exists

- name: create a service for next reboot to disable transparent hugepage
  template:
    src: disable-thp.service.j2
    dest: /etc/systemd/system/disable-thp.service

- name: enable the disable-thp service
  service: name=disable-thp enabled=yes

- name: Disable transparent huge page - defrag
  shell: echo "never" > /sys/kernel/mm/transparent_hugepage/defrag
 
- name: Disable transparent huge page - enabled
  shell: echo "never" > /sys/kernel/mm/transparent_hugepage/enabled
 
- name: VM swappiness - 1
  shell: echo "1" > /proc/sys/vm/swappiness
 
- name: Set VM swappiness - 2
  sysctl:
    name: vm.swappiness
    value: 1
    state: present

- name: Enable firewalld
  service: name=firewalld state=started enabled=yes

- name: Set dmz as default policy
  command: firewall-cmd --set-default-zone=dmz

- name: allow ntp through firewall
  shell: firewall-cmd --add-service=ntp --permanent

- name: firewall reload
  shell: firewall-cmd --reload
  # when: inventory_hostname in groups['masters']

- name: Make sure Chrony is started up
  service: name=chronyd state=started enabled=yes
  tags: chrony
  # when: inventory_hostname in groups['masters']

- name: set timezone
  shell: timedatectl set-timezone Asia/Singapore

- name: Install NTP
  yum: name=ntp state=installed 
  tags: ntp

- name: Copy over the NTP configuration
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  notify:
  - restart ntpd
  tags: ntp

- name: Make sure NTP is stopped
  service: name=ntpd state=stopped enabled=yes
  tags: ntp

# - name: Sync time initialy
#   shell: ntpdate {{hostvars[groups['masters'][0]]['inventory_hostname']}}
#   tags: ntp

- name: Make sure NTP is started up
  service: name=ntpd state=started enabled=yes
  tags: ntp

- name: Sync hwclock
  shell: hwclock -w
  tags: ntp

- name: Open up FirewallD ports for all the services (This will need to be cut down to what's required)
  command: "firewall-cmd --zone=dmz --add-port={{item}}/tcp --permanent"
  with_items:
    - 22
    - "{{cloudera_ports}}"
    - "{{cdh_services_ports}}"
    - "{{cdh_third_party_ports}}"
- name: reload firewalld
  command: firewall-cmd --reload