---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Sample Template.'
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.small
    ConstraintDescription: must be a valid EC2 instance type.
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  ImageId:
    Description: Image Id of the ami to use
    Type: String
    ConstraintDescription: must be the name of an existing ami Id
Resources:
  HdpEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType:
        Ref: InstanceType
      SecurityGroups:
      - Ref: InstanceSecurityGroup
      KeyName:
        Ref: KeyName
      ImageId:
        Ref: ImageId
      Tags:
        - Key: Name
          Value:
            Ref: AWS::StackName
      UserData: 
        Fn::Base64: 
          !Sub |
            #!/bin/bash -xe
            rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
            yum -y install python-pip
            /bin/easy_install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
            # Install Ansible from the metadata
            pip install ansible
            git clone https://github.com/amitthk/cloudformhadoopstak.git
            cd cloudformhadoopstak
            ansible-playbook --connection=local -i hosts -vvvv main.yml &> ansible_install.log
    Metadata:
      AWS::CloudFormation::Init:
        configSets:
          bootstrapit:
            - "install-packages"
            - "install-ansible"
        install-packages:
          packages:
            yum:
              gcc-c++: []
              autoconf: []
              automake: []
              python-pip: []
              httpd: []
        install-ansible:
          commands:
            0-install-pip:
              command: sudo easy_install pip
            1-sleep:
              command: sleep 10s
            2-install-ansible:
              command: sudo pip install ansible
            3-sleep:
              command: sleep 10s
            4-print-ansible-version:
              command: ansible --version
            5-pause-after-ansible:
              command: sleep 10s
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp:
          Ref: SSHLocation
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value:
      Ref: HdpEC2Instance
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value:
      Fn::GetAtt:
      - HdpEC2Instance
      - AvailabilityZone
  PublicDNS:
    Description: Public DNSName of the newly created EC2 instance
    Value:
      Fn::GetAtt:
      - HdpEC2Instance
      - PublicDnsName
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value:
      Fn::GetAtt:
      - HdpEC2Instance
      - PublicIp
